version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Java"
      - sudo yum install -y java-17-amazon-corretto-17.0.11+9-1.amzn2023.1.x86_64
      - sudo yum install maven -y
    


  build:
    commands:
      - echo "Testing with Maven"
      - mvn --version
      - cd my-app
      - mvn clean package
      
