# name: Java CI with Maven

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# env:
#   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         cache: maven

#     - name: Build with Maven
#       run: mvn -B package
#       working-directory: my-app

#     - name: Set up Node 14
#       uses: actions/setup-node@v3
#       with:
#         node-version: 14

#     - name: Install Snyk CLI
#       run: npm install -g snyk

#     - name: Authenticate Snyk CLI
#       run: snyk auth ${{ secrets.SNYK_TOKEN }}

#     - name: Run Snyk Open Source Test
#       run: snyk test
#       working-directory: my-app

#     - name: Run Snyk Code Test
#       run: snyk code test
#       working-directory: my-app
